<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>Trakit.Sync</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Trak-iT API Synchronization</Title>
		<PackageProjectUrl>https://apis.trakit.ca/dotnet</PackageProjectUrl>
		<AssemblyName>Trakit.$(MSBuildProjectName)</AssemblyName>
		<AssemblyVersion>0.3.0.0</AssemblyVersion>
		<FileVersion>0.3.0.0</FileVersion>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>0.3.0.0</Version>
		<PackageIcon>it_128.png</PackageIcon>
		<Copyright>2024 Traki-iT Wireless Inc.</Copyright>
		<Authors>Trak-it Wireless Inc.</Authors>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\trakit-dotnet\it_128.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\trakit-dotnet\commands\Commands.csproj" />
		<ProjectReference Include="..\..\trakit-dotnet\objects\Objects.csproj" />
	</ItemGroup>
</Project>